# Use the official Perl image from DockerHub
FROM perl:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Install the required Perl modules
RUN cpan install \
    Text::CSV::Simple \
    Data::Dumper \
    PDL \
    PDL::Fit::Polynomial \
    Statistics::Descriptive \
    Math::Random \
    Math::Interpolate \
    Getopt::Long

# Copy the local script to the container
COPY ./weka-preprocessor.perl .

EXPOSE $PERL_PREPROCESSOR_PORT
